# ==========================================
# 1. SETUP DEL VIEWER
# ==========================================
/vis/open OGL 600x600-0+0
/vis/viewer/set/autoRefresh false
/vis/drawVolume

# Impostiamo la telecamera sull'asse Y per guardare il piano XZ dritto di fronte a noi
/vis/viewer/set/viewpointThetaPhi 90 90
# Diciamo a Geant4 che l'asse Z è "l'alto"
/vis/viewer/set/upVector 0 0 1
/vis/viewer/zoom 1.5

# ==========================================
# 2. SETUP DELLE TRAIETTORIE
# ==========================================
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/scene/endOfEventAction accumulate

# ==========================================
# 3. GPS SETUP (Sorgente 2D nel piano XZ)
# ==========================================
/gps/particle proton
/gps/energy 10 MeV

# 3A. LA GEOMETRIA: Un cilindro piatto (anello)
/gps/pos/type Surface
/gps/pos/shape Cylinder
/gps/pos/radius 60. cm
/gps/pos/halfz 0.1 mm
/gps/pos/centre 0. 0. 0. cm

# Ruotiamo l'asse dell'anello in modo che giaccia esattamente sul piano XZ
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 0 1

# 3B. LA CINEMATICA: Confinamento nel piano 2D
/gps/ang/type iso
# Schiacciamo l'emissione isotropa bloccandola sull'equatore dell'anello
# In questo modo p_y (momento fuori dal piano) sarà rigorosamente ZERO!
/gps/ang/mintheta 90. deg
/gps/ang/maxtheta 90. deg

# ==========================================
# 4. ESECUZIONE
# ==========================================
/vis/viewer/set/autoRefresh true

# Ne spariamo 500 perché, essendo direzioni casuali sul piano 2D, 
# metà andranno verso l'esterno e metà andranno dritte verso il tuo scudo
/run/beamOn 1000

# /control/execute ../macros/vis_ring.mac